apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-33md
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-33md@sha256:cd3c6e43294a31f5230e243f45b204be29f7f73c87039d5d7423975d491a5c2e
        name: my-nodejs
        resources: {}
status: {}
